name: Build and Deploy Docker to Azure

on:
  push:
    branches:
      - toCrmFS

permissions:
  id-token: write
  contents: read

env:
  REGISTRY: myfirstprojectacr.azurecr.io
  IMAGE_NAME: myfirstproject
  WEBAPP_NAME: myFirstProject
  RESOURCE_GROUP: Anu1982

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.0e9c69f7-50b6-4e54-923a-aa78e271d09f }}
          tenant-id: ${{ secrets.db892ef3-1711-48c5-a6a9-d4af49591b71 }}
          subscription-id: ${{ secrets.c5295c2a-cf8b-4eba-9085-1ce7ddfeaf6d }}

      - name: Login to ACR
        run: |
          az acr login --name myfirstprojectacr

      - name: Build Docker Image
        run: |
          docker build \
            -t $REGISTRY/$IMAGE_NAME:${{ github.sha }} \
            -t $REGISTRY/$IMAGE_NAME:latest .

      - name: Push Docker Image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:${{ github.sha }}
          docker push $REGISTRY/$IMAGE_NAME:latest

      - name: Configure Web App Container
        run: |
          az webapp config container set \
            --resource-group $RESOURCE_GROUP \
            --name $WEBAPP_NAME \
            --container-image-name $REGISTRY/$IMAGE_NAME:latest

      - name: Restart Web App
        run: |
          az webapp restart \
            --resource-group $RESOURCE_GROUP \
            --name $WEBAPP_NAME
